GET http://localhost:3003/api/blogs HTTP/1.1

###

POST http://localhost:3003/api/blogs/636d250b672b6934c3975b02/comments
Content-Type: application/json

{
    "content": "awesome article"
}

###
POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYzNGZlMDE4NTQ1MzJlYTliY2FhZmIyYiIsImlhdCI6MTY2NjI2NjQ1NSwiZXhwIjoxNjY2MzUyODU1fQ.liUF5fh1eJHoXMUlkMNUi980_dnD9xksd7eCAbXeKpA

{
    "title": "findById is working with rest client or not",
    "author":"mr struggle with tests",
    "url": "Superuser.com",
    "likes": "0"
}

####
GET http://localhost:3003/api/blogs/634fe590ae47affefa8b6296 HTTP/1.1


# logged in as root user, salainen password, username: Superuser 
####
DELETE http://localhost:3003/api/blogs/63512e5acf05cd0c8923a547 HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYzNGZlMDE4NTQ1MzJlYTliY2FhZmIyYiIsImlhdCI6MTY2NjI1Njk4NywiZXhwIjoxNjY2MzQzMzg3fQ.nllbvpmxJ7Kdc0eBwh3aV-Ch_k1YwQGhjLD3hTUrCj0